# 版本号
version: "3"
# 自定义网络
networks:
  # 网络名字
  huasenNetwork:
    # 网关驱动
    driver: bridge
# 容器服务
services:
  # 服务名称
  mongo:
    # 安装镜像
    image: mongo:4.2.2
    # 容器名称
    container_name: mongo
    restart: always
    volumes:
      # /data/db数据目录挂载到宿主机
      - ./huasen-mongo/volume:/data/db
      # 记录终端输出
      - ./huasen-mongo/tail/null:/huasen-mongo/tail/null
      # init-mongo-open.js 文件会在 mongodb 容器初始化完成之后执行，创建数据库默认的角色
      - ./huasen-mongo/init-mongo-open.js:/docker-entrypoint-initdb.d/init-mongo-open.js
    # 执行命令，windows 系统下，设置 15 秒的睡眠时间，避免 mongo 没有启动，执行初始化脚本失败
    command: sh -c "mongod --bind_ip 0.0.0.0 & sleep 15 && mongo /docker-entrypoint-initdb.d/init-mongo-open.js && tail -f /huasen-mongo/tail/null"
    environment:
      # 设置时区为上海（东八区）
      TZ: Asia/Shanghai
      # 初始化mongodb的账户，账户创建在admin下，拥有超管权限
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo12345*
    ports:
      # 将容器的27017端口映射到宿主机的27017端口
      - 37017:27017
    networks:
      - huasenNetwork

  redis:
    image: redis:6.0.10-alpine
    container_name: redis
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 7379:6379
    volumes:
      - ./huasen-redis/conf/redis-open.conf:/usr/local/etc/redis/redis.conf
      - ./huasen-redis/data:/data:rw
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - huasenNetwork

  nginx:
    # 使用ottps实现SSL专用nginx镜像
    # image: ohttps/ohttps-nginx
    image: nginx:1.23.1
    container_name: nginx
    restart: always
    volumes:
      - ./huasen-nginx/conf/nginx-open.conf:/etc/nginx/nginx.conf
      - ./huasen-nginx/www:/home/www
      - ./huasen-nginx/log:/var/log/nginx
      - ./huasen-nginx/html:/usr/share/nginx/html
    ports:
      # 宿主机:容器
      - 80:80
    environment:
      - TZ=Asia/Shanghai
      # ohttps部署节点id
      # - PUSH_NODE_ID=push-***
      # ohttps部署节点令牌
      # - PUSH_NODE_TOKEN=***
    networks:
      - huasenNetwork

  # jenkins:
  #   image: jenkins/jenkins:lts
  #   container_name: jenkins
  #   restart: always
  #   privileged: true
  #   user: root
  #   volumes:
  #     # 挂载目录到容器
  #     - ./huasen-jenkins/:/var/jenkins_home
  #     - ./huasen-jenkins-cache:/huasen-jenkins-cache
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - TZ=Asia/Shanghai
  #   networks:
  #     - huasenNetwork

  server:
    # 指定Dockerflie构建镜像
    build:
      context: .
      dockerfile: huasen-server/Dockerfile
    # 定义容器名称
    container_name: server
    restart: always
    privileged: true
    user: root
    # 挂载日志、静态文件目录、依赖库、服务参数、项目配置、前端构建包
    volumes:
      - ./huasen-store/:/app/huasen-store
      - ./huasen-log/:/app/huasen-server/log
      - ./huasen-server/setting.json:/app/huasen-server/setting.json
      - ./huasen-server/config.js:/app/huasen-server/config.js
      - ./huasen-server/public/webapp/:/app/huasen-server/public/webapp/
    ports:
      - "3000:3000"
      - "8181:8181"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mongo
      - redis
    networks:
      - huasenNetwork
